name : Bash Script Workflow

on:
  push:
    branches:
      - main
      - '/*'

jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Bash script syntax check
        run: |
          if bash -n script.sh; then
            echo "No Syntax Error"
          else
            echo "Syntax Error"
            exit 1

        

        
          




      





